### ISSUE TITLE
Endpoint per obtenir token

### ISSUE THREAD

**Issue by spdvi** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#1]
No hi ha informació sobre el endpoint per obtenir el token i el format i variables en el que se li ha de passar l'usuari i la password que hi ha al Readme.

**Comment by ainaperalta** [comment]
Hem actualitzat el readme i l'ajuda de l'API amb la guia de com s'ha de fer el login. Creim que està ben explicat, però si teniu algun dubte més ho demanau :)

**Comment by spdvi** [comment]
Perfect. Now it is working.
Thanks
