### ISSUE TITLE
No es posible acceder a la imagen de un artista en concreto

### ISSUE THREAD

**Issue by Roberto-Garijo** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#10]
Buenas, he intentado hacer la petición a la api como me habeis dicho en el anterior issue y tampoco ha funcionado, no puedo acceder a la imagen de ninguna manera

![image](https://user-images.githubusercontent.com/77688938/156614021-4df47b54-9557-41a6-ae3a-ccc3fc0cf361.png)

**Comment by EricGoyenechea** [comment]
This endpoint does not exist, in the api you have all the  available endpoints.

**Comment by Roberto-Garijo** [comment]
Entonces cual es el endpoint para que me bien la url de la imagen que quiero obtener?

**Comment by spdvi** [comment]
Which is the url of the folder in which you are storing the images?
We have tried many combinations but there seems to be no correct path...
http://baleart.tomeuvich.com/exemple-app/public/api/imatges/4.jpg
http://baleart.tomeuvich.com/exemple-app/public/api/imatges/artistes/4.jpg
All return not found.
Do the images 1.jpg, 2.jpg, etc. exist at all in the server?
