### ISSUE TITLE
No existe un endpoint para hacer get de las exposiciones con sus espacios

### ISSUE THREAD

**Issue by Roberto-Garijo** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#12]
Buenas, en la documentación de la api se puede hacer post y delete de las relaciones entre un espacio y sus exposiciones pero no puedo hacer un get de estas exposiciones por su espacio, por lo tanto no puedo tratar la información. Lo considero que lo apropiado sería crear un endpoint para conseguir todas las exposiciones por su id de espacio.

**Comment by EricGoyenechea** [comment]
Hecho
