### ISSUE TITLE
Respecto a la subida de imágenes

### ISSUE THREAD

**Issue by Jorge-Collado** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#14]
Buenas

Hemos visto que el endpoint que nos permite postear imágenes acepta como parámetro únicamente una URL
![image](https://user-images.githubusercontent.com/77398684/156623937-bb69623c-e8b4-4258-a9b3-1f75048d5ce0.png)

Consideramos que esto es ineficiente puesto a que requiere que la imagen tenga que estar subida con anterioridad en otro servidor, nos facilitaría mucho el trabajo que pudiesemos subir directamente el archivo de la imagen

**Comment by ainaperalta** [comment]
El tema de las imágenes ya está prácticamente solucionado, se pueden subir y eliminar imágenes en "Exposicions", "Espais", "Obres", "Artistes" y "Usuaris". Los endpoints que salen en la imagen que has pasado mejor no utilizarlos, porque se subiría la imagen a la BBDD pero no crearía ninguna relación con ninguna tabla y sería una imagen perdida.
