### ISSUE TITLE
POST afegir espais 

### ISSUE THREAD

**Issue by pauprats2002** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#15]
Buenas, me el siguiente error a la hora de insertar un nuevo espacio en la query.
![image](https://user-images.githubusercontent.com/77688104/157484860-1c86e564-669c-4e4c-8129-2d278ba5c887.png)
No se si falta algun campo o es un problema interno. Esperamos vuestra respuesta, gracias.

**Comment by Tomeu-Vich** [comment]
Ja està arreglat
