### ISSUE TITLE
Modificación de los resultados de la API

### ISSUE THREAD

**Issue by Jorge-Collado** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#16]
Hemos notado que habeis modificado los resultados de todos los endpoints de la API de forma muy significativa, esto y perdón por la expresión, nos ha jodido puesto a que en nuestra app ya no funciona nada de lo que teniamos. 
Sería posible tener dos versiones de los endpoints?? Una con los resultados de antes que necesitamos nosotros y otra con los actuales que usaís vosotros puesto a que nuestro proyecto se entrega mañana y como espero entendais no tenemos tiempo de rehacer todo.

Muchas gracias ^^

**Comment by spdvi** [comment]
Estaba probando el proyecto cliente ahora y me ha pasado lo mismo. Si habeis hecho cambios lo deberiais haber anunciado primero al menos y sobretodo haber mantenido la compatibilidad con lo que había anteriormente. Hay muchas horas de trabajo que dependen de vuestra API.
Por favor devolverla al estado anterior o hacer los cambios de forma que no se rompan nuestros proyectos.
Gracias

**Comment by spdvi** [comment]
Ok ya está hablado. En un par de horas lo revertirán.

**Comment by spdvi** [comment]
El problema es que ahora por ejemplo en el login nos devuelve:
```
{
        "status": "Login OK",
        "result": {
                "token": "U25ydjBkZll5cklsMXhQa2hsOE50MmJjbVRpcE5FTWVyempkM0x0dQ==",
                "id": 13,
                "nomUsuari": "client"
        }
}
```
y antes devolvía:
```
{
    "status": "Login OK",
    "result": "U25ydjBkZll5cklsMXhQa2hsOE50MmJjbVRpcE5FTWVyempkM0x0dQ=="
}
```
por lo que al mapearlo y deserializarlo a nuestro objeto Java nos salta una excepción porqué en nuestro objeto Java el campo result es un String y ahora es un objeto de otro tipo.
Si se hubiera hecho como:
```
{
    "status": "Login OK",
    "result": "U25ydjBkZll5cklsMXhQa2hsOE50MmJjbVRpcE5FTWVyempkM0x0dQ==",
    "id": 13,
    "nomUsuari": "client"
}
```
no hubiera habido problema.
Podemos adaptar en un momento en login pero todos los demás que han cambiado lleva más trabajo.

**Comment by Tomeu-Vich** [comment]
Buenas, ya hemos hecho la presentación de nuestra aplicación y la api ya está en su estado inicial. Si tenéis algún problema más, nos lo podéis decir. Perdonad por las molestias no sabíamos que os podía problemas.
