### ISSUE TITLE
No puedo enlazar comentarios ni con usuarios ni con espacios

### ISSUE THREAD

**Issue by Roberto-Garijo** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#18]
Buenas, a la hora de hacer un post de una valoración, no existe endpoint en donde le pase id de usuario o id de espai, por lo tanto al crearlo, no se puede saber a que espacio se valora o que usuario valora un espacio.

![image](https://user-images.githubusercontent.com/77688938/157698714-1b1475b8-d008-4cb0-a55f-cc93f6faac2a.png)

El POST de usuarios solo admite 3 parametros, "dataValoracio", "comentari" i "puntuacio". 
Creemos que lo ideal seria hacer un post de estos 3 campos y además el id de un usuario y el id de un espacio.

Gracias

**Comment by ainaperalta** [comment]
Ya está, para el POST se necesitan los parámetros: "dataValoracio", "comentari", "puntuacio", "usuaris_id", "espais_id"; y para el PUT los mismos más "revisat", que es un boolean.
