### ISSUE TITLE
Respuesta del post en el endpoint de login

### ISSUE THREAD

**Issue by Roberto-Garijo** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#19]
Buenas, hemos visto que se han restaurado los resultados de algunas peticiones de la api, pero vemos que el login no, seria posible que volviera a estar como antes? O en su defecto, estaría bien un formato del siguiente estilo:

![image](https://user-images.githubusercontent.com/77688938/157732130-bcbb5462-b36a-49cd-9a4f-ca67da4bc2dc.png)

Gracias y un saludo

**Comment by Roberto-Garijo** [comment]
No se si el resto de endpoints se han restaurado también pero si se pudiera restaurar todo como estaba antes sería ideal, perdon por las molestias y un saludo

**Comment by Tomeu-Vich** [comment]
Ya esta como estaba antes el log in.
