### ISSUE TITLE
Los endpoints tiran todos status 500

### ISSUE THREAD

**Issue by Jorge-Collado** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#4]
Da igual que endpoints usemos todos  tiran server status 500
![image](https://user-images.githubusercontent.com/77398684/154295211-d39e2fd7-2bdb-495d-bea6-5ff9077252c8.png)

**Comment by ainaperalta** [comment]
![image](https://user-images.githubusercontent.com/77160815/154299656-68edd0b3-e253-4603-a648-01722505e12b.png)

**Comment by ainaperalta** [comment]
Los nombres de los parámetros están mal, serian "correuElectronic" y "contrasenya". Aun así, tenéis meterle los parámetros por "x-www-form-urlencoded" en lugar de un JSON. Nosotros hemos estado haciendo pruebas y todos funcionan.
