### ISSUE TITLE
Límite de caracteres de parámetros.

### ISSUE THREAD

**Issue by pauprats2002** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#5]
Buenas, hemos notado que algunos parámetros tienen un límite de caracteres bastante corto y nos gustaría saber si podríais especificarnos éstos, gracias.

**Comment by Tomeu-Vich** [comment]
He deixat l'arxiu amb la creació de la base de dades per a que pogueu comprovar el tamany dels strings. Si necessitau que canviem formats, ho podem fer.
