### ISSUE TITLE
Endpoints de relaciones 

### ISSUE THREAD

**Issue by Jorge-Collado** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#6]
Buenas, hemos visto que hay endpoints para relacionar varios objetos entre ellos (Exposiciones con espacios, obras con artistas, espacios con idiomas, etc..)
Pero no hay (o no lo hemos visto nosotros) uno para obtener que objetos están relacionados entre si, ej: obtener la descripción de un espacio en un idioma específico
![image](https://user-images.githubusercontent.com/77398684/154978189-9a0a3da0-10c0-4c50-9dd7-0e9d5fceddda.png)
Si se pudiesen crear endpoints de get sobre las tablas de las relaciones nos facilitaria mucho el trabajo
Gracias de antemano

**Comment by EricGoyenechea** [comment]
Hecho
