### ISSUE TITLE
Coger espacio con OFFSET y LIMIT

### ISSUE THREAD

**Issue by pauprats2002** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#7]
Buenas, querriamos pedir si en la API se podria implementar un GET para poder coger una cierta cantidad de obras en vez de todas. Gracias.

**Comment by EricGoyenechea** [comment]
Creemos que este trabajo lleva mas trabajo realizarlo en el servidor que en el cliente

**Comment by spdvi** [comment]
En mi opinión debería estar en el servidor por varios motivos. El principal es que no es nada eficiente (en velocidad, en el tamaño de la transferencia) enviar "todas" las obras de la tabla de la BBDD, o todos los espais... Si son 7 igual vale pero, y si fueran 1000 o 1M? La aplicación debería estar preparada para poder ser escalada y para eso se necesita poder "paginar" las peticiones para ir descargando los datos "a demanda" del usuario. ¿Imaginais que instagram descargara todos los posts en un feed al iniciar la aplicación?
