### ISSUE TITLE
Error 500 en el endpoint    GET/tipusespais/{tipus}

### ISSUE THREAD

**Issue by Jorge-Collado** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#8]
Al usar este endpoint nos encontramos con un code 500 a pesar de poner un tipus valido, creemos que se debe a que la query busca una columna "id" en la tabla "espaitipus" pero al revisar el SQL vemos que esta tabla solo tiene una columna llamada "tipus"
![image](https://user-images.githubusercontent.com/77398684/156395244-ca14dea0-a64c-451c-9f2f-fc3d97e9576a.png)

Ejemplo de la peticion que hacemos
![image](https://user-images.githubusercontent.com/77398684/156395849-906e979e-b6ce-4273-9ee5-66f7a9605f21.png)

**Comment by Tomeu-Vich** [comment]
Ja està arreglat.
