### ISSUE TITLE
No es posible hacer un get de una imagen en concreto

### ISSUE THREAD

**Issue by Roberto-Garijo** [CIFP-Pau-Casesnoves-DAW/baleart-public-eric-aina-tomeu#9]
Buenas, cuando en el postman intento hacer el get a la url en cuestión, me salta error 404.

![image](https://user-images.githubusercontent.com/77688938/156438250-9fa437a3-5751-4d60-b134-49df08de125d.png)

**Comment by Tomeu-Vich** [comment]
L'id de la imatge no és 1.jpg, sinó 1.

**Comment by spdvi** [comment]
I quina es la url del fitxer de la imatge? No podem descarregar les imatges si no tenim la url completa. Estan les imatges pujades al servidor?
